version: "3"
services:
  web:
    build: apache
    env_file: 
      - .env    
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./apache/drupaloracle.conf:/etc/apache2/sites-enabled/drupaloracle.conf
      - ./html:/html
      - ./apache/certificados:/certificados
